kind: pipeline
type: docker
name: default

workspace:
  base: /home
  path: commission

steps:
- name: buildwar
  image: gradle:jdk8
  commands:
  - echo "" > /etc/apt/sources.list
  - echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main restricted\ndeb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates main restricted\ndeb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial universe\ndeb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates universe\ndeb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial multiverse\ndeb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates multiverse\ndeb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted\ndeb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security universe \ndeb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security multiverse" >> /etc/apt/sources.list
  - apt-get update
  - apt-get install sshpass
  - gradle test
  - gradle jar --debug
  - sshpass -p openjaw scp -o 'StrictHostKeyChecking no' build/libs/eureka.jar root@192.168.22.148:/root/ftp/
