kind: pipeline
type: docker
name: default

workspace:
  base: /home
  path: commission

steps:
- name: buildwar
  image: gradle:jdk8
  commands:
  - pwd
  - wget http://mirrors.163.com/.help/sources.list.jessie -O /etc/apt/sources.list
  - apt-get update
  - apt-get install sshpass
  - gradle test
  - gradle war
  - sshpass -p openjaw scp build/libs/commission-1.0.war root@192.168.22.148:/root/ftp/commission-1.0.war
