workspace:
  base: /home
  path: commission
 
pipeline:
  build:
    image: java:openjdk-8
  environment:
    - GRADLE_USER_HOME=~/.gradle
  commands:
    - pwd
    - wget http://mirrors.163.com/.help/sources.list.jessie -O /etc/apt/sources.list
    - apt-get update
    - apt-get install sshpass
    - ./gradlew test
    - ./gradlew war
    - sshpass -p openjaw scp build/libs/commission-1.0.war root@192.168.22.148:/root/ftp/commission-1.0.war
 
ssh-deploy:
  image: appleboy/drone-ssh
  pull: true
  host: 192.168.22.148
  user: root
  password: openjaw
  port: 22
  command_timeout: 180
  script:
    - cd /root/ftp
    - ll
  when:
    branch: [master]
    event: [push]
